/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.store": [],
    "logout": [],
    "password.request": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.email": [],
    "password.store": [],
    "register": [],
    "register.store": [],
    "user-profile-information.update": [],
    "user-password.update": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "profile.show": [],
    "other-browser-sessions.destroy": [],
    "current-user-photo.destroy": [],
    "sanctum.csrf-cookie": [],
    "products.index": [],
    "products.create": [],
    "products.store": [],
    "products.show": [
        {
            "name": "product",
            "required": true
        }
    ],
    "products.edit": [
        {
            "name": "product",
            "required": true
        }
    ],
    "products.update": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "products.destroy": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard": [],
    "places.index": [],
    "places.create": [],
    "places.store": [],
    "places.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "places.edit": [
        {
            "name": "id",
            "required": true
        }
    ],
    "places.update": [
        {
            "name": "id",
            "required": true
        }
    ],
    "places.destroy": [
        {
            "name": "id",
            "required": true
        }
    ],
    "places.nearby": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance.edit": [],
    "two-factor.show": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
